### ISSUE TITLE
no sequncer generated after sending large value tx

### ISSUE THREAD

**Issue by metabd** [annchain/OG#5]
no sequncer generated after sending large value tx , Garantee is 1.4 million

**Comment by heeeeeng** [comment]
Due to incorrectly check of TxPool.isBadTx() function, a piece of large guarantee transactions will destroy the confirm process of Sequencers.
This is fixed by commit [b0118fd](https://github.com/annchain/OG/commit/b0118fd3d8cd09a52b4b8c89e3e758e53b5691ea)
